PROX_dir: ./POSA_dir/PROXD
affordance_dir: ./POSA_dir/affordance
affordance_lr: 1.0
affordance_step: 0.2
base_dir: ./POSA_dir/
batch_size: 64
block_size: 1
channels: 64
checkpoint_path: ./POSA_dir/trained_models/contact_semantics.pt
cond_dim: 0
config: cfg_files/contact_semantics.yaml
contact_threshold: 0.05
contact_w: 1.0
data_dir: ./POSA_dir/data
down_sample: 2
drop_out: false
ds_us_dir: ./POSA_dir/mesh_ds
epochs: 15
f_dim: 1
float_dtype: float32
gender: male
h_dim: 512
input_dim: 2619
kl_w: 0.1
load_checkpoint: 0
log_interval: 5
loss_type: bce
lr: 0.001
make_collage: true
max_init_points: 10
max_iter: 30
model_folder: ./POSA_dir/smplx_models
no_obj_classes: 42
normalization_mode: group_norm
num_groups: 8
num_hidden_layers: 3
num_init_points: 3
num_pca_comps: 6
num_rand_samples: 3
num_rendered_samples: 1
num_workers: 0
nv: 655
opt_pose: true
out_dim: 1
output_dir: ./POSA_dir/trained_models/contact_semantics
pen_w: 10.0
pose_w: 100.0
rand_samples_dir: ./POSA_dir/random_samples
recording_name: ''
recordings_list: null
reduce_lr: false
reduction: mean
render: true
rp_base_dir: ./POSA_dir/rp_clothed_meshes
save_checkpoints: true
save_dir: ./save/debug_sample02_rep00_iter=100_sofa
save_meshes: true
scene_name: MPH11
semantics_w: 1.0
seq_length: 9
show_contact: false
show_gen_sample: false
show_init_pos: false
show_scene: false
show_semantics: false
shuffle: true
specified_object: sofa
step: 1
tensorboard: false
test: true
test_recordings_list: null
train_data: false
train_recordings_list: null
trunc_val: 0.5
up_sample: false
use_clothed_mesh: false
use_cuda: true
use_semantics: true
viz: false
x_dim: 655
z_dim: 256
